CREATE DATABASE ESCUELA_PROYECTO;
USE ESCUELA_PROYECTO; 
CREATE TABLE CURSOS (ID_CURSO VARCHAR(5) PRIMARY KEY CONSTRAINT, NOMBRE_CURSO VARCHAR(50) NOT NULL, ISBN VARCHAR(25) NOT NULL, SEMESTRE int(2) NOT NULL;